auth:
  # 認證方式選擇
  prefer_adc: true  # 優先使用 Application Default Credentials
  
  # OAuth 2.0 設定 (當 ADC 不可用時使用)
  credentials_file: credentials.json
  port: 9876
  token_file: token.pickle
  
  # API 權限範圍
  scopes:
  - https://www.googleapis.com/auth/drive.readonly
  
  # ADC 設定
  adc:
    # 如果 ADC 失敗，是否回退到傳統的 OAuth 流程
    fallback_to_oauth: true
database:
  echo: false
  url: sqlite:///data/downloads.db
download:
  chunk_size: 1048576
  max_concurrent: 5
  max_retries: 3
  output_directory: ./downloads
  retry_delay: 1.0
  timeout: 300
logging:
  backup_count: 5
  file: logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_size: 10485760
ui:
  progress_update_interval: 1.0
  theme: light
web:
  debug: false
  host: 127.0.0.1
  port: 8000
